app/flaskexpenses/transactions/models.py
# -*- coding: utf-8 -*-
"""User models."""
from datetime import datetime

from elasticsearch_dsl import DocType, String, Date, Boolean, Float


class Trx(DocType):
    type = String(index='not_analyzed')
    amount = Float()
    account = String(index='not_analyzed')
    account_type = String(index='not_analyzed')
    description = String()
    trx_date = Date()
    created_date = Date()
    tags = String(index='not_analyzed', multi=True)
    payee = String(index='not_analyzed')
    
    class Meta:
        index = 'flexpenses'

    def save(self, ** kwargs):
        if not self.created_date:
            self.created_date = datetime.now()
        return super(Trx, self).save(kwargs)

app/flaskexpenses/user/models.py
# -*- coding: utf-8 -*-
"""User models."""
import datetime as dt

from flask_login import UserMixin

from flaskexpenses.database import Column, Model, SurrogatePK, db, reference_col, relationship
from flaskexpenses.extensions import bcrypt


class Role(SurrogatePK, Model):
    """A role for a user."""

    __tablename__ = 'roles'
    name = Column(db.String(80), unique=True, nullable=False)
    user_id = reference_col('users', nullable=True)
    user = relationship('User', backref='roles')

    def __init__(self, name, **kwargs):
        """Create instance."""
        db.Model.__init__(self, name=name, **kwargs)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<Role({name})>'.format(name=self.name)


class User(UserMixin, SurrogatePK, Model):
    """A user of the app."""

    __tablename__ = 'users'
    username = Column(db.String(80), unique=True, nullable=False)
    email = Column(db.String(80), unique=True, nullable=False)
    #: The hashed password
    password = Column(db.String(128), nullable=True)
    created_at = Column(db.DateTime, nullable=False, default=dt.datetime.utcnow)
    first_name = Column(db.String(30), nullable=True)
    last_name = Column(db.String(30), nullable=True)
    active = Column(db.Boolean(), default=False)
    is_admin = Column(db.Boolean(), default=False)

    def __init__(self, username, email, password=None, **kwargs):
        """Create instance."""
        db.Model.__init__(self, username=username, email=email, **kwargs)
        if password:
            self.set_password(password)
        else:
            self.password = None

    def set_password(self, password):
        """Set password."""
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, value):
        """Check password."""
        return bcrypt.check_password_hash(self.password, value)

    @property
    def full_name(self):
        """Full user name."""
        return '{0} {1}'.format(self.first_name, self.last_name)

    def __repr__(self):
        """Represent instance as a unique string."""
        return '<User({username!r})>'.format(username=self.username)

app/flaskexpenses/transactions/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import  StringField, DateTimeField
from wtforms.fields.core import DecimalField, SelectField
from wtforms.fields.simple import TextAreaField
from wtforms.validators import DataRequired, Length
from wtforms.widgets.core import HTMLString, html_params, TextArea


class TransactionForm(Form):
    """Transaction form."""

    type = SelectField(
        'Transaction Type',
        choices=[('expense', 'Expense'), ('Income', 'Income')]
    )
    account = SelectField(
        'Account',
        choices=[('Stratos Cash', 'Stratos Cash'), ('Arzu Cash', 'Arzu Cash'), ('text', 'Plain Text')]
    )
    amount = DecimalField('Amount', places=2,
                        validators=[DataRequired(), ])
    
    # The date format has to mimic the moment.js format set in:
    # templates/transactions/new.html
    trx_date = DateTimeField('Transaction Date', format="%A, %B %d %Y, %H:%M")

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(TransactionForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(TransactionForm, self).validate()
        if not initial_validation:
            return False

        return True

class BulkImportForm(Form):
    """Transaction form."""

    data = TextAreaField()
    
    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(BulkImportForm, self).__init__(*args, **kwargs)

    def validate(self):
        """Validate the form."""
        initial_validation = super(BulkImportForm, self).validate()
        if not initial_validation:
            return False

        return True

app/flaskexpenses/user/forms.py
# -*- coding: utf-8 -*-
"""User forms."""
from flask_wtf import Form
from wtforms import PasswordField, StringField
from wtforms.validators import DataRequired, Email, EqualTo, Length

from .models import User


class RegisterForm(Form):
    """Register form."""

    username = StringField('Username',
                           validators=[DataRequired(), Length(min=3, max=25)])
    email = StringField('Email',
                        validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password',
                             validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Verify password',
                            [DataRequired(), EqualTo('password', message='Passwords must match')])

    def __init__(self, *args, **kwargs):
        """Create instance."""
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.user = None

    def validate(self):
        """Validate the form."""
        initial_validation = super(RegisterForm, self).validate()
        if not initial_validation:
            return False
        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append('Username already registered')
            return False
        user = User.query.filter_by(email=self.email.data).first()
        if user:
            self.email.errors.append('Email already registered')
            return False
        return True

app/flaskexpenses/__init__.py
"""Main application package."""

app/flaskexpenses/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory function."""
from elasticsearch_dsl.connections import connections
from flask import Flask, render_template
from flask_jsglue import JSGlue

from flaskexpenses import public, user, transactions
from flaskexpenses.assets import assets
from flaskexpenses.extensions import bcrypt, cache, csrf_protect, db, debug_toolbar, login_manager, migrate
from flaskexpenses.settings import ProdConfig
from flaskexpenses.transactions.models import Trx


def create_app(config_object=ProdConfig):
    """An application factory, as explained here: http://flask.pocoo.org/docs/patterns/appfactories/.

    :param config_object: The configuration object to use.
    """
    app = Flask(__name__)
    app.config.from_object(config_object)
    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    
    connections.create_connection(hosts=[config_object.ELASTICSEARCH], timeout=20)
    Trx.init()
    
    return app


def register_extensions(app):
    """Register Flask extensions."""
    assets.init_app(app)
    bcrypt.init_app(app)
    cache.init_app(app)
    db.init_app(app)
    csrf_protect.init_app(app)
    login_manager.init_app(app)
    debug_toolbar.init_app(app)
    migrate.init_app(app, db)
    
    jsglue = JSGlue()
    jsglue.init_app(app)
    
    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(public.views.blueprint)
    app.register_blueprint(user.views.blueprint)
    app.register_blueprint(transactions.views.blueprint)
    return None


def register_errorhandlers(app):
    """Register error handlers."""
    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template('{0}.html'.format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)
    return None

app/flaskexpenses/transactions/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""


from . import views, ajax  # noqa

app/flaskexpenses/transactions/views.py
# -*- coding: utf-8 -*-
"""User views."""
import StringIO
import csv
from datetime import datetime

from elasticsearch.client import Elasticsearch
from elasticsearch_dsl.query import Q
from elasticsearch_dsl.search import Search
from flask import Blueprint, render_template, redirect
from flask.globals import request
from flask.helpers import flash, url_for

from flaskexpenses.transactions.forms import TransactionForm, BulkImportForm
from flaskexpenses.transactions.models import Trx
from flaskexpenses.transactions.utils import find_oldest_trx_date_and_sum, \
    get_total_balance, get_totals_per_account_type
from flaskexpenses.utils import flash_errors


blueprint = Blueprint('transactions', __name__, url_prefix='/transactions', static_folder='../static')


@blueprint.route('/')
def dashboard():
    """List members."""
    

    total_balance = get_total_balance()
    total_cash, total_cc, total_bank = get_totals_per_account_type()
  
    return render_template('transactions/dashboard.html',
                           total_balance=total_balance,
                           total_cash=total_cash,
                           total_cc=total_cc,
                           total_bank=total_bank)


@blueprint.route('/new', methods=['GET', 'POST'])
def new():
    """Add new Transaction."""
    form = TransactionForm(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        t = Trx()
        t.type = form.type.data
        t.amount = form.amount.data
        t.account = form.account.data
        t.trx_date = form.trx_date.data
        t.save()
        
        flash('Thank you for registering. You can now log in.', 'success')
        return redirect(url_for('transactions.home'))
    else:
        flash_errors(form)

    return render_template('transactions/new.html', form=form)


@blueprint.route('/graphs')
def graphs():
    """List members."""
    return render_template('transactions/kibana.html')

@blueprint.route('/import', methods=['GET', 'POST'])
def bulk_import():
    form = BulkImportForm(request.form, csrf_enabled=False)
    if form.validate_on_submit():
        _bulk_import(form.data.data)
        
        flash('Your data has been imported', 'success')
        return redirect(url_for('transactions.home'))
    else:
        flash_errors(form)

    return render_template('transactions/import.html', form=form)

def _bulk_import(data):
    print "Bulk importing"
    f = StringIO.StringIO(data)
    reader = csv.reader(f, delimiter=',')
    now = datetime.now()
    
    for row in reader:
        
        trx = Trx()
        
        trx.created_date = now
        
        trx.trx_date = row[0]
        
        trx.type = row[1]
        
        trx.amount = row[2]
        
        if row[3]:
            trx.tags.append(row[3])
            
        if row[4]:
            trx.tags.append(row[4])
            
        trx.description = row[5]
        
        trx.payee = row[6]
        
        trx.account = row[7]
        
        trx.account_type = row[8]
        
        trx.save()
        
        print '\t'.join(row)

app/flaskexpenses/user/__init__.py
# -*- coding: utf-8 -*-
"""The user module."""
from . import views  # noqa

app/flaskexpenses/user/views.py
# -*- coding: utf-8 -*-
"""User views."""
from flask import Blueprint, render_template
from flask_login import login_required

blueprint = Blueprint('user', __name__, url_prefix='/users', static_folder='../static')


@blueprint.route('/')
@login_required
def members():
    """List members."""
    return render_template('users/members.html')

app/flaskexpenses/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

app/flaskexpenses/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="pull-right hidden-xs">
    You know... for expenses!
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2016 <a href="{{ url_for('public.about') }}">Stratos Gerakakis</a>.</strong> All rights reserved.
</footer>

app/flaskexpenses/templates/header.html
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <a href="index2.html" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>A</b>LT</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>FL</b>expenses</span>
  </a>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">

        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs">Logged in User</span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

              <p>
                Logged in User
                <small>Member since Nov. 2012</small>
              </p>
            </li>
            <!-- Menu Footer-->
            <li class="user-footer">
              <div class="pull-left">
                <a href="#" class="btn btn-default btn-flat">Profile</a>
              </div>
              <div class="pull-right">
                <a href="#" class="btn btn-default btn-flat">Sign out</a>
              </div>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/flaskexpenses/templates/layout.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block page_title %}

    Flask Expenses

    {% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  {% include "header.html" %}

  {% include "nav.html" %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    
    {% if self.header() %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block header %}{% endblock %}
        <small>{% block subheader %}{% endblock %}</small>
      </h1>
    </section>
    {% endif %}

    <!-- Main content -->
    <section class="content">

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-ban"></i> {{ category|upper }}!</h4>
                        {{message}}
                </div>
            {% endfor %}
        {% endif %}
        {% endwith %}

      <!-- Your Page Content Here -->
      {% block content %}{% endblock %}

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  {% include "footer.html" %}

</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->

<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
</body>
</html>

app/flaskexpenses/templates/nav.html
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu">
      <li class="header">Options</li>
      <!-- Optionally, you can add icons to the links -->
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('transactions.graphs') }}">Graphs</a></li>
      <li><a href="{{ url_for('transactions.bulk_import') }}">Import</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>

    </ul>
    <!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>